#!/bin/sh -v

perl="perl -I ."
do="require A;"

export PERL5LIB=".:$PERL5LIB"
$perl -v | grep 'This is perl'

# these should pass

: standard perl
$perl            -e "$do" || { echo "probe failed unexpectedly!"; exit 1; }

: perl with debugger in NonStop mode
export PERLDB_OPTS="NonStop"
$perl -d         -e "$do" || { echo "probe failed unexpectedly!"; exit 1; }

# these currently fail with perl 5.8.6

: perl with stub debugger
$perl -d:stub    -e "$do" && { echo "probe passed unexpectedly!"; exit 1; }

: perl with NYTProf
export NYTPROF=${NYTPROF}:stmts=0:blocks=0:start=no:subs=0:slowops=0:leave=0
$perl -d:NYTProf -e "$do" && { echo "probe passed unexpectedly!"; exit 1; }

