# Profile data generated by Devel::NYTProf::Reader
# More information at http://search.cpan.org/dist/Devel-NYTProf/
# Format: time,calls,time/call,code
~2,1,0,$code = eval 'sub { sleep 2; }';
0,1,0,$code->();
