# Profile data generated by Devel::NYTProf::Reader
# Author: Adam Kaplan. More information at http://search.cpan.org/~akaplan
# Format: time,calls,time/call,code
0,1,0,1;
0,1,0,DB::disable_profile();
0,0,0,1;
0,0,0,DB::enable_profile();
0,1,0,1;
