# Profile data generated by Devel::NYTProf::Reader
# More information at http://search.cpan.org/dist/Devel-NYTProf/
# Format: time,calls,time/call,code
0,0,0,# Testing various types of eval calls. Some are processed differently internally
0,0,0,
0,0,0,sub foo {
0,3,0,print "in sub foo\n";
0,0,0,}
0,0,0,
0,0,0,sub bar {
0,1,0,print "in sub bar\n";
0,0,0,}
0,0,0,
0,0,0,sub baz {
0,1,0,print "in sub baz\n";
0,2,0,eval { foo();  # counts as two executions
0,1,0,foo(); }; # counts as one execution
0,2,0,eval { x(); # counts as two executions, fails out of eval
0,0,0,x(); }; # 0 executions. never gets here
0,0,0,}
0,0,0,
0,1,0,eval "foo();";  # one vanilla execution, one eval execution
0,2,0,eval { bar(); };  # two executions
0,1,0,baz();
