# Profile data generated by Devel::NYTProf::Reader v.0.01
# Author: Adam Kaplan. More information at http://search.cpan.org/~akaplan
# Format: time,calls,time/call,code
0,0,0,sub foo {
0,2,0,eval "1;
0,0,0,2;
0,0,0,bar();";
0,0,0,}
0,0,0,
0,0,0,sub bar {
0,3,0,eval "3;";
0,0,0,}
0,0,0,
0,1,0,foo();
0,1,0,foo();
0,1,0,bar();
