# Profile data generated by Devel::NYTProf::Reader v.0.01
# Author: Adam Kaplan. More information at http://search.cpan.org/~akaplan
# Format: time,calls,time/call,code
0,0,0,sub foo {
0,4,0,print "in sub foo\n";
0,4,0,bar();
0,0,0,}
0,0,0,
0,0,0,sub bar {
0,13,0,print "in sub bar\n";
0,0,0,}
0,0,0,
0,0,0,sub baz {
0,2,0,print "in sub baz\n";
0,2,0,bar();
0,2,0,bar();
0,2,0,bar();
0,2,0,foo();
0,0,0,}
0,0,0,
0,1,0,bar();
0,0,0,
0,2,0,fork;
0,0,0,
0,2,0,bar();
0,2,0,baz();
0,2,0,foo();
